POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "content": "Testi"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mauri Ernesti",
    "number": "123-456-789"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "123456789"
}

###
POST https://shielded-ridge-17530.herokuapp.com/api/persons
Content-Type: application/json

{
    "content": "Testi"
}

###

POST https://shielded-ridge-17530.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Mauri Ernesti",
    "number": "123-456-789"
}